# Generated by Django 3.2.8 on 2021-10-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('customer_name', models.CharField(max_length=15, null=True)),
                ('reservation_date_and_time', models.DateTimeField()),
                ('number_of_customers', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('user', 'customer_name', 'reservation_date_and_time')},
            },
        ),
    ]
