# Generated by Django 3.2.8 on 2021-10-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('In', 'Inside'), ('Out', 'Outside')], max_length=3)),
                ('table_number', models.IntegerField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
