# Generated by Django 3.2.8 on 2021-10-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-reservation_date_and_time']},
        ),
    ]
