# Generated by Django 3.2.8 on 2021-10-25 16:56

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date_and_time',
            field=models.DateTimeField(blank=True, null=True, validators=[restaurant.models.Booking.validate_date]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer_name', 'reservation_date_and_time')},
        ),
    ]
