# Generated by Django 3.2.8 on 2021-10-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20211025_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer_name', 'reservation_date_and_time')},
        ),
    ]
