# Generated by Django 3.2.8 on 2021-10-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_number',
        ),
    ]
