# Generated by Django 3.2.8 on 2021-10-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer_name', 'reservation_date_and_time')},
        ),
    ]
