# Generated by Django 3.2.8 on 2021-10-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_table_table_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
