# Generated by Django 3.2.8 on 2021-10-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_availabletables_booking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_table', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='table',
            name='number_of_tables_available',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to='restaurant.availabletable'),
        ),
        migrations.DeleteModel(
            name='AvailableTables',
        ),
    ]
