# Generated by Django 3.2.8 on 2021-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20211016_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletable',
            name='available_table',
            field=models.IntegerField(default='1'),
        ),
    ]
