# Generated by Django 3.2.8 on 2021-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_availabletable_available_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number_of_tables_available',
        ),
        migrations.AddField(
            model_name='table',
            name='available_table',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='AvailableTable',
        ),
    ]
