# Generated by Django 3.2.8 on 2021-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20211016_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available_table',
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=2),
        ),
    ]
