# Generated by Django 3.2.8 on 2021-10-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20211016_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='available_tables',
            field=models.IntegerField(default=15),
        ),
    ]
