# Generated by Django 3.2.8 on 2021-10-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_table_available_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available_tables',
        ),
        migrations.RemoveField(
            model_name='table',
            name='category',
        ),
    ]
