# Generated by Django 3.2.8 on 2021-10-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_booking_menu_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
