# Generated by Django 3.2.8 on 2021-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_booking_menu_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(choices=[('A la carte', 'A la carte'), ('House special', 'Special'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=13),
        ),
    ]
