# Generated by Django 3.2.8 on 2021-10-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_menu_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('Seats2', 'Couple'), ('Seats4', 'Family of 4'), ('Seats6', 'Family of 6'), ('Seats10', 'Large Party')], max_length=7),
        ),
    ]
