# Generated by Django 3.2.8 on 2021-10-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_availabletables_booking_menu_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableTables',
            new_name='AvailableTable',
        ),
    ]
