# Generated by Django 3.2.8 on 2021-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_rename_availabletables_availabletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='tables_available',
        ),
        migrations.AlterField(
            model_name='booking',
            name='menu',
            field=models.CharField(choices=[('A la carte', 'A la carte'), ('House special', 'Special'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan')], max_length=13),
        ),
        migrations.DeleteModel(
            name='AvailableTable',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
