# Generated by Django 3.2.8 on 2021-10-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_auto_20211017_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='user',
        ),
    ]
