# Generated by Django 3.2.8 on 2021-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_rename_customer_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='available_tables',
            field=models.IntegerField(default=1),
        ),
    ]
