# Generated by Django 3.2.8 on 2021-10-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_table_available_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='available_tables',
            new_name='avail_tables',
        ),
    ]
