# Generated by Django 3.2.8 on 2021-10-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_auto_20211017_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='avail_tables',
        ),
    ]
