# Generated by Django 3.2.8 on 2021-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_remove_booking_avail_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='avail_tables',
            field=models.IntegerField(default=1),
        ),
    ]
