# Generated by Django 3.2.8 on 2021-10-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_auto_20211017_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='available_tables',
            new_name='avail_tables',
        ),
    ]
