# Generated by Django 3.2.8 on 2021-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_rename_available_tables_booking_avail_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='avail_tables',
        ),
    ]
