# Generated by Django 3.2.8 on 2021-10-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_table_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='at',
        ),
    ]
