# Generated by Django 3.2.8 on 2021-10-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_remove_table_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_customers',
        ),
    ]
