# Generated by Django 3.2.8 on 2021-10-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_remove_booking_number_of_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_customers',
            field=models.IntegerField(default=1),
        ),
    ]
