# Generated by Django 3.2.8 on 2021-10-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_booking_number_of_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_tables',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
