# Generated by Django 3.2.8 on 2021-10-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_auto_20211017_1917'),
        ('restaurant', '0044_booking'),
    ]

    operations = [
    ]
