# Generated by Django 3.2.8 on 2021-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_auto_20211017_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
