# Generated by Django 3.2.8 on 2021-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
