# Generated by Django 3.2.8 on 2021-10-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0046_auto_20211019_1150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('customer', 'start_date', 'end_date', 'number_of_customers', 'menu')},
        ),
    ]
