# Generated by Django 3.2.8 on 2021-10-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0048_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer', 'start_date', 'end_date', 'number_of_customers', 'menu')},
        ),
    ]
