# Generated by Django 3.2.8 on 2021-10-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0053_alter_booking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
    ]
