# Generated by Django 3.2.8 on 2021-10-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0054_remove_booking_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='reservation_date',
        ),
    ]
