# Generated by Django 3.2.8 on 2021-10-22 16:16

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0055_auto_20211022_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateTimeField(blank=True, default=None, null=True, validators=[restaurant.models.Booking.validate_date]),
        ),
    ]
