# Generated by Django 3.2.8 on 2021-10-23 20:01

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0056_alter_booking_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date_and_time',
            field=models.DateTimeField(blank=True, null=True, validators=[restaurant.models.Booking.validate_date]),
        ),
    ]
