# Generated by Django 3.2.8 on 2021-10-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0057_auto_20211023_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer_name', 'reservation_date_and_time', 'number_of_customers')},
        ),
    ]
