# Generated by Django 3.2.8 on 2021-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0058_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_customers',
            field=models.IntegerField(null=True),
        ),
    ]
